name: Whatever
on: [push, pull_request]

jobs:
  label:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
    - name: Test
      run: whoami
      shell: bash